schema_version = "1.0.0"
id = "blender_lut_exporter"
version = "2.0.0"
name = "LUT Exporter & Importer"
tagline = "Converts adjustment layer into LUT .cube file and back"
maintainer = "ichlubna <ichlubna@fit.vut.cz>"
type = "add-on"
website = "https://github.com/ichlubna/BlenderLUTExporter"
tags = ["Import-Export", "Sequencer"]
blender_version_min = "5.0.0"
license = ["SPDX:GPL-3.0-or-later"]
